package main

import (
	"bytes"
	"testing"

	"github.com/matryer/is"
)

func TestRender(t *testing.T) {
	cases := map[string]struct {
		input    Data
		expected string
	}{
		"basic events": {
			input: Data{
				Package:   "mypackage/foo",
				UnionName: "eventTypes",
				TypeName:  "EventType",
				Fields: []Field{
					{
						Name:  "CREATED",
						Doc:   "Thing was created",
						Value: "created",
					},
				},
			},
			expected: `// Generated code; DO NOT EDIT
// This file was generated by goconst from mypackage/foo

export const eventTypes = [
	// Thing was created
	"created",
] as const;

export type EventType = typeof eventTypes[number];
`,
		},
		"no fields": {
			input: Data{
				Package:   "mypackage/foo",
				UnionName: "eventTypes",
				TypeName:  "EventType",
				Fields:    []Field{},
			},
			expected: `// Generated code; DO NOT EDIT
// This file was generated by goconst from mypackage/foo

export const eventTypes = [] as const;

export type EventType = typeof eventTypes[number];
`,
		},
	}

	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			is := is.New(t)
			result := new(bytes.Buffer)
			r := NewRenderer(result)

			err := r.Render(tc.input)
			is.NoErr(err)
			is.Equal(tc.expected, result.String())
		})
	}
}
